---
- hosts: hosts
  user: ubuntu
  become: True
  tasks:
    - block:
        - name: Get Modern PIP
          get_url:
            url: "https://bootstrap.pypa.io/get-pip.py"
            dest: "/opt/get-pip.py"
            force: "yes"
          register: get_pip
          until: get_pip | success
          retries: 5
          delay: 2
          tags:
            - pip-install-script

      rescue:
        - name: Get Modern PIP using fallback URL
          get_url:
            url: "https://raw.githubusercontent.com/pypa/get-pip/master/get-pip.py"
            dest: "/opt/get-pip.py"
            force: "yes"
          when: get_pip | failed
          register: get_pip_fallback
          until: get_pip_fallback | success
          retries: 5
          delay: 2
          tags:
            - pip-install-script

    - block:
        - name: Install PIP
          shell: |
            python /opt/get-pip.py
          register: pip_install
          until: pip_install | success
          retries: 3
          delay: 2

      rescue:
        - name: Install PIP (fall back mode)
          shell: |
            python /opt/get-pip.py --isolated
          register: pip_install_fall_back
          until: pip_install_fall_back | success
          retries: 3
          delay: 2
