- hosts: hosts
  user: ubuntu
  become: True
  tasks:
    - name: Pip package
      pip:
        name: "{{ item }}"
      with_items:
        - pyaml
        - python-openstackclient
        - rpc-zigzag
